### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by selfhoster1312** [comment]
Wow you're so quick! I guess you already saw that but navidrome v0.49 includes https://github.com/navidrome/navidrome/pull/2087 so SSOWat should be plug & play (authenticate users via HTTP headers and create accounts in DB automatically).

How can i upgrade my navidrome to the testing branch without removing/reinstalling (and losing the DB in the process)?

**Comment by selfhoster1312** [comment]
!testme

**Comment by ericgaspar** [comment]
For this upgrade, we are regenerating the configuration file to add the new entries. This will overwrite the custom settings to default. The DB should be untouched.

**Pull request merged**
